## Ejercicio 1

En la celda de código siguiente crea un dataframe llamado frutas que tenga esta estructura: 
<br><br>
<img src="imgs/ej-01.PNG">

In [1]:
import pandas as pd

In [10]:
frutas = pd.DataFrame({'Manzanas': 30, 'Platanos': 21}, index=[0])
frutas

   Manzanas  Platanos
0        30        21

## Ejercicio 2

Crea un dataframe llamado ventas_frutas que encaje con la siguiente foto:

<br>

<img src="imgs/ej-01.2.PNG">

In [12]:
ventas_frutas = pd.DataFrame({'Manzanas': [35, 41], 'Platanos': [21, 34]}, index=['Ventas 2017', 'Ventas 2018'])
ventas_frutas

             Manzanas  Platanos
Ventas 2017        35        21
Ventas 2018        41        34

## Ejercicio 3

Crea una variable ingredientes que sea una serie con este contenido:

<img src="imgs/ej-01.3.PNG">

In [18]:
ingredientes = pd.Series(['4 tazas', '1 taza', '2 unidades XL', '1 pieza'], 
                         index=['Harina', 'Azucar', 'Huevos', 'Mantequilla'], 
                         name='cena')
ingredientes

Harina               4 tazas
Azucar                1 taza
Huevos         2 unidades XL
Mantequilla          1 pieza
Name: cena, dtype: object

## Ejercicio 4

Lee el dataset llamado **datos_casas_india.csv** que está en la ruta **/Dia-02/datasets/datos_casas_india.csv** en una variable de tipo dataframe y llámalo casas_india, finalmente muestra su contenido.

In [25]:
casas_india = pd.read_csv('../datasets/datos_casas_india.csv')
casas_india.head()

,house_type,house_size,location,city,latitude,longitude,price,currency,numBathrooms,numBalconies,isNegotiable,priceSqFt,verificationDate,description,SecurityDeposit,Status
0,1 RK Studio Apartment,400 sq ft,Kalkaji,Delhi,28.545561,77.254349,22000,INR,1.0,NaN,NaN,NaN,Posted a day ago,"Fully furnished, loaded with amenities & gadge...",No Deposit,Furnished
1,1 RK Studio Apartment,400 sq ft,Mansarover Garden,Delhi,28.643259,77.132828,20000,INR,1.0,NaN,NaN,NaN,Posted 9 days ago,Here is an excellent 1 BHK Independent Floor a...,No Deposit,Furnished
2,2 BHK Independent Floor,500 sq ft,Uttam Nagar,Delhi,28.618677,77.053352,8500,INR,1.0,NaN,NaN,NaN,Posted 12 days ago,"Zero Brokerage.\r\n\r\n2 Room set, Govt bijali...",No Deposit,Semi-Furnished
3,3 BHK Independent House,"1,020 sq ft",Model Town,Delhi,28.712898,77.180000,48000,INR,3.0,NaN,NaN,NaN,Posted a year ago,Itâs a 3 bhk independent house situated in M...,No Deposit,Furnished
4,2 BHK Apartment,810 sq ft,Sector 13 Rohini,Delhi,28.723539,77.131424,20000,INR,2.0,NaN,NaN,NaN,Posted a year ago,Well designed 2 bhk multistorey apartment is a...,No Deposit,Unfurnished

## Ejercicio 5

Ejecuta la siguiente celda para crear un dataframe llamado animales y crea una celda extra en la que se escriba ese dataframe en un fichero CSV en la ruta **/Dia-02/datasets/animales.csv**

In [26]:
animales = pd.DataFrame({'Vacas': [12, 20], 'Cabras': [22, 19]}, index=['Año 1', 'Año 2'])
animales

       Vacas  Cabras
Año 1     12      22
Año 2     20      19

In [30]:
animales.to_csv('../datasets/animales.csv', index=True)